openapi: 3.0.3
info:
  title: EigenDB REST API
  description: REST API for EigenDB.
  version: 1.0.0
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Eigen-API-Key
  schemas:
    embeddingSchema:
      type: object
      properties:
        data:
          type: array
          items:
            type: number
            format: float
          description: The embedding's data
        id:
          type: integer
          description: The embedding's ID
        metadata:
          type: object
          description: The embedding's metadata (set to {} for empty metadata)
      required:
        - data
        - id
        - metadata
    responseSchema:
      type: object
      properties:
        status:
          type: integer
          description: Status code of the response
        message:
          type: string
          description: Message giving basic information on the response
        data:
          type: object
          description: Important data to be given to the caller
        error:
          type: object
          description: An error that has occured
          properties:
            code:
              type: string
              description: An error code unique to this type of error
            description:
              type: string
              description: A detailed description of the error
      required:
        - status
        - message
paths:
  /health:
    get:
      summary: Database health check
      operationId: healthCheck
      description: Perform a health check on the database.
      security: []
      responses:
        '200':
          description: Database is healthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: healthy
                data:
                  cpu_usage_percent: 0.06
                  mem_usage_percent: 1.31
                  uptime: 72h3m0.5s
        '500':
          description: Database is unhealthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 500
                message: unhealthy
                error:
                  code: ERROR_GETTING_CPU_USAGE
                  description: detailed description of the error...
  /test-auth:
    get:
      summary: Test your authentication
      operationId: testAuth
      description: Test your authentication using your API key.
      responses:
        '200':
          description: Authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: Authenticated.
        '401':
          description: Invalid API key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 401
                message: Invalid API key.
                error:
                  code: INVALID_API_KEY
                  description: The API key you provided is invalid.
  /indexes/list:
    get:
      summary: List all index names
      operationId: listIndexes
      description: List the names of all indexes that currently exist.
      responses:
        '200':
          description: Stats fetched successfully. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: Indexes listed successfully
                data:
                  indexes: 
                    - "hello-world"
                    - "fubar"
                    - "some-thing"
        '500':
          description: An error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 500
                message: An error occured while listing indexes.
                error:
                  code: INDEXES_NOT_LISTED
                  description: detailed description of the error...
  /indexes/{indexName}/stats:
    get:
      summary: Get stats of an index
      operationId: getIndexStats
      description: Get stats of an index containing its information. 
      parameters:
        - name: indexName
          in: path
          description: Name of the index
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Stats fetched successfully. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: Stats for index 'my-index' fetched successfully.
                data:
                  index_name: 'my-index'
                  dimensions: 1536
                  metric: 'cosine'
        '500':
          description: An error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 500
                message: An error occured while fetching the index.
                error:
                  code: INDEX_NOT_FETCHED
                  description: detailed description of the error...
  /indexes/{indexName}/create:
    put:
      summary: Create an index
      operationId: createIndex
      description: Create an index with given specifications.
      parameters:
        - name: indexName
          in: path
          description: Name of the index
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - dimensions
                - metric
              properties:
                dimensions:
                  type: number
                  format: integer
                  description: Dimensions of the index
                metric:
                  type: string
                  description: The similarity metric for the index
      responses:
        '200':
          description: Index created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: Index '<indexName>' created successfully.
        '500':
          description: Invalid similarity metric (currently supporting cosine, l2, ip)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 500
                message: An error occured while creating the index.
                error:
                  code: INVALID_SIMILARITY_METRIC
                  description: detailed description of the error...
  /indexes/{indexName}/delete:
    delete:
      summary: Delete an index
      operationId: deleteIndex
      description: Delete an index given its name.
      parameters:
        - name: indexName
          in: path
          description: Name of the index
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Index successfully deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: Index '<indexName>' successfully deleted.
        '500':
          description: An error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 500
                message: An error occured while deleting the index.
                error:
                  code: INDEX_NOT_DELETED
                  description: detailed description of the error...
  /embeddings/{indexName}/insert:
    put:
      summary: Insert embeddings
      operationId: insertEmbeddings
      description: Inserts a set of embeddings into the database.
      parameters:
        - name: indexName
          in: path
          description: Name of the index
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - embeddings
              properties:
                embeddings:
                  type: array
                  items:
                    type: object
                    $ref: '#/components/schemas/embeddingSchema'
                  description: Embeddings to be inserted.
      responses:
        '200':
          description: Embedding successfully inserted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: 50/50 embeddings successfully inserted.
        '500':
          description: An internal server error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 500
                message: 49/50 embeddings successfully inserted.
                error:
                  code: EMBEDDINGS_SKIPPED
                  description: detailed description of the error...
  /embeddings/{indexName}/upsert:
    put:
      summary: Upsert embeddings
      operationId: upsertEmbeddings
      description: Upserts a set of embeddings into the database (insert and update embedding if it already exists).
      parameters:
        - name: indexName
          in: path
          description: Name of the index
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - embeddings
              properties:
                embeddings:
                  type: array
                  items:
                    type: object
                    $ref: '#/components/schemas/embeddingSchema'
                  description: Embeddings to be upserted.
      responses:
        '200':
          description: Embedding successfully upserted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: 50/50 embeddings successfully upserted.
        '500':
          description: An internal server error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 500
                message: 49/50 embeddings successfully upserted.
                error:
                  code: EMBEDDINGS_SKIPPED
                  description: detailed description of the error...
  /embeddings/{indexName}/delete:
    delete:
      summary: Delete embeddings
      operationId: deleteEmbeddings
      description: Delete a set of embeddings using IDs.
      parameters:
        - name: indexName
          in: path
          description: Name of the index
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ids
              properties:
                ids:
                  type: array
                  items:
                    type: number
                    format: integer
                  description: IDs of embedding to delete
      responses:
        '200':
          description: Embeddings successfully deleted..
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: 2/2 embeddings successfully deleted.
        '500':
          description: An internal server error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 500
                message: 1/2 embeddings successfully deleted.
                error:
                  code: EMBEDDINGS_SKIPPED
                  description: 
                    - embedding with ID 87 was not deleted - embedding with ID 87 does not exist
  /embeddings/{indexName}/retrieve:
    post:
      summary: Retrieve embeddings
      operationId: retrieveEmbeddings
      description: Retrieve a set of embeddings using IDs.
      parameters:
        - name: indexName
          in: path
          description: Name of the index
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ids
              properties:
                ids:
                  type: array
                  items:
                    type: number
                    format: integer
                  description: IDs of embedding to retrieve
      responses:
        '200':
          description: Embeddings successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: 2/2 embeddings successfully retrieved.
                data:
                  embeddings:
                    - data: [0.1, -0.2, 0.45]
                      id: 23
                      metadata:
                        foo: bar
                    - data: [0.2, -0.7, 0.32]
                      id: 67
                      metadata: {}
        '500':
          description: An internal server error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 500
                message: 1/2 embeddings successfully retrieved.
                data:
                  embeddings:
                    - data: [0.1, -0.2, 0.45] 
                      id: 23
                      metadata:
                        foo: bar
                error:
                  code: EMBEDDINGS_SKIPPED
                  description: 
                    - embedding with ID 87 was not retrieved - embedding with ID 87 does not exist
  /embeddings/{indexName}/search:
    post:
      summary: Search for embeddings
      operationId: searchEmbedding
      description: Search for embeddings using vector similarity search
      parameters:
        - name: indexName
          in: path
          description: Name of the index
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - queryVector
                - k
              properties:
                queryVector:
                  type: array
                  items:
                    type: number
                    format: float
                  description: ID of the query vector
                k:
                  type: number
                  format: int
                  description: Number of retrieved embedding desired. 
      responses:
        '200':
          description: The k-nearest embeddings returned in an array along with their rank (0 is nearest).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 200
                message: Similarity search successfully performed.
                data:
                  nearest_neighbors:
                    54:
                      metadata:
                        foo: bar
                      rank: 0
                    98:
                      metadata:
                        foo1: bar2
                        bar: baz
                      rank: 1
                    21:
                      metadata:
                        foo3: bar4
                      rank: 2
                    63:
                      metadata:
                        foo5: bar6
                        hello: world
                      rank: 3
                    45:
                      metadata:
                        foo7: bar8
                      rank: 4
        '400':
          description: An error occured when performing similarity search.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSchema'
              example:
                status: 400
                message: An error occured during the similarity search.
                error:
                  code: SIMILARITY_SEARCH_ERROR
                  description: detailed description of the error...
  # /update-config/persistence/time-interval:
  #   post:
  #     summary: Update persistence interval
  #     operationId: updatePersistenceTimeInterval
  #     description: Modify the time interval at which vectors in memory are persisted on disk.
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             required:
  #               - updatedValueSecs
  #             properties:
  #               updatedValueSecs:
  #                 type: number
  #                 format: float
  #                 description: The new time interval in seconds
  #     responses:
  #       '200':
  #         description: Time interval successfully updated.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/responseSchema'
  #             example:
  #               status: 200
  #               message: Time interval updated.
  #       '500':
  #         description: An error occured.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/responseSchema'
  #             example:
  #               status: 500
  #               message: An error occured.
  #               error:
  #                 code: ERROR_UPDATING_PERSISTENCE_TIME_INTERVAL
  #                 description: detailed description of the error...
  # /update-config/api/port:
  #   post:
  #     summary: Update the API port
  #     operationId: updateApiPort
  #     description: Update the port on which the API runs (default = 8080). EigenDB must be restarted this to take effect.
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             required:
  #               - updatedPort
  #             properties:
  #               updatedPort:
  #                 type: number
  #                 format: int
  #                 description: The new port number
  #     responses:
  #       '200':
  #         description: API port successfully updated.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/responseSchema'
  #             example:
  #               status: 200
  #               message: API port updated. Please restart the database for it to take effect.
  #       '500':
  #         description: An error occured.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/responseSchema'
  #             example:
  #               status: 500
  #               message: An error occured.
  #               error:
  #                 code: ERROR_UPDATING_API_PORT
  #                 description: detailed description of the error...
  # /update-config/api/address:
  #   post:
  #     summary: Update the API address
  #     operationId: updateApiAddress
  #     description: Update the address on which the API runs (default = 0.0.0.0). EigenDB must be restarted this to take effect.
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             required:
  #               - updatedAddress
  #             properties:
  #               updatedAddress:
  #                 type: string
  #                 description: The new API address
  #     responses:
  #       '200':
  #         description: API address successfully updated.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/responseSchema'
  #             example:
  #               status: 200
  #               message: API address updated. Please restart the database for it to take effect.
  #       '500':
  #         description: An error occured.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/responseSchema'
  #             example:
  #               status: 500
  #               message: An error occured.
  #               error:
  #                 code: ERROR_UPDATING_API_ADDRESS
  #                 description: detailed description of the error...
  # /update-config/hnsw-params/similarity-metric:
  #   post:
  #     summary: Update the similarity metric
  #     operationId: updateSimilarityMetric
  #     description: Update the similarity metric used in similarity search (default = euclidean). EigenDB must be restarted this to take effect.
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             required:
  #               - updatedMetric
  #             properties:
  #               updatedMetric:
  #                 type: string
  #                 description: The new similarity metric (cosine, euclidean, ip)
  #     responses:
  #       '200':
  #         description: Similarity metric successfully updated.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/responseSchema'
  #             example:
  #               status: 200
  #               message: Vector similarity metric updated. Please restart the database for it to take effect.
  #       '400':
  #         description: Invalid similarity metric.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/responseSchema'
  #             example:
  #               status: 400
  #               message: Something went wrong when trying to update the similarity metric.
  #               error:
  #                 code: INVALID_SIMILARITY_METRIC
  #                 description: detailed description of the error...
  #       '500':
  #         description: An error occured.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/responseSchema'
  #             example:
  #               status: 500
  #               message: An error occured.
  #               error:
  #                 code: ERROR_UPDATING_SIMILARITY_METRIC
  #                 description: detailed description of the error...
